# Generated by Django 3.0.3 on 2020-02-24 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20200224_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='maketime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
